# Generated by Django 5.2.7 on 2025-10-15 16:08

import django.db.models.deletion
import poke.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('idTipoPokemon', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'TipoPokemon',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=180)),
                ('dtInclusao', models.DateTimeField(auto_now_add=True)),
                ('dtAlteracao', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', poke.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('idPokemonUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('imagemUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('grupoBatalha', models.BooleanField(default=False)),
                ('favorito', models.BooleanField(default=False)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
                ('tipos', models.ManyToManyField(related_name='pokemons', to='poke.tipopokemon')),
            ],
            options={
                'db_table': 'PokemonUsuario',
            },
        ),
    ]
