services:
  api:
    command: /start
    container_name: api_backend
    build:
      context: .
    env_file:
      - ./.environment/.env.django
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static

volumes:
  static_volume:
